---
id: Kolab_Session
name: Kolab_Session
full: Kolab session management library
description: This package stores Kolab specific user data in the session.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Kolab_Session
authors:
  -
    name: Gunnar Wrobel
    user: wrobel
    email: p@rdus.de
    active: true
    role: lead
version:
  release: 2.0.4
  api: 1.1.0
state:
  release: stable
  api: stable
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/Horde_Exception: ^2
  optional:
    pear:
      pear.horde.org/Horde_Imap_Client: ^2
      pear.horde.org/Horde_Kolab_Server: ^2
      pear.horde.org/Horde_Log: ^2
      pear.horde.org/Horde_Test: ^2.1
